version: '3.2'
services:
  app:
    ports:
      - "8085:8085"
    image: mslabko/magento_performance_demo
    command: /bin/sh -c "/start_services.sh"
    working_dir: /var/www/html
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  xhgui:
    image: duhon/xhgui
    depends_on:
      - mongodb
    ports:
      - "0.0.0.0:8088:80"
    volumes:
      - ./etc/mongo/mongo.php:/tmp/mongo.php
    command: /bin/sh -c "php /tmp/mongo.php && php -S 0.0.0.0:80 -t /var/xhgui/webroot"
